name: rayforge
adopt-info: rayforge
confinement: strict
base: core24

apps:
  rayforge:
    extensions: [gnome]
    command: bin/rayforge
    common-id: org.rayforge.rayforge
    desktop: share/applications/org.rayforge.rayforge.desktop
    plugs:
      - home
      - gsettings
      - network
      - network-bind
      - removable-media
      - x11
      - wayland
      - opengl
      - camera
      - shared-memory
      - serial-port
    environment:
      GI_TYPELIB_PATH: $SNAP/usr/lib/x86_64-linux-gnu/girepository-1.0
      PYTHONPATH: $SNAP/lib/python3.12/site-packages:$SNAP/usr/lib/python3/dist-packages
      LD_LIBRARY_PATH: $SNAP/gnome-platform/usr/lib/x86_64-linux-gnu/libproxy:$SNAP/usr/lib/rayforge-libs
      LD_PRELOAD: $SNAP/bin/semwraplib.so

slots:
  rayforge:
    interface: dbus
    bus: session
    name: org.rayforge.rayforge

parts:
  semwraplib:
    plugin: dump
    source: snap
    override-build: |
      mkdir -p ../install/bin
      gcc -g -O0 -Wall -Wstrict-prototypes -fPIC -shared semwraplib.c -o ../install/bin/semwraplib.so -ldl
    build-packages:
      - build-essential

  rayforge:
    plugin: python
    source: .
    python-requirements:
      - requirements.txt
    build-packages:
      - python3-pip
      - python3-setuptools
      - libvips-dev
      - git  # Required for git describe
    stage-packages:
      - libvips42t64
    parse-info: [share/metainfo/org.rayforge.rayforge.metainfo.xml]
    override-pull: |
      craftctl default
      craftctl set version="$(git describe --tags)"
    override-build: |
      # Create a single, generic directory for all our custom-staged libs
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/lib/rayforge-libs

      # Symlink ALL required libraries into our new generic directory
      ln -s ../x86_64-linux-gnu/libvips.so.42 $SNAPCRAFT_PART_INSTALL/usr/lib/rayforge-libs/libvips.so.42
      ln -s ../x86_64-linux-gnu/libfftw3.so.3 $SNAPCRAFT_PART_INSTALL/usr/lib/rayforge-libs/libfftw3.so.3
      ln -s ../x86_64-linux-gnu/libcfitsio.so.10 $SNAPCRAFT_PART_INSTALL/usr/lib/rayforge-libs/libcfitsio.so.10
      ln -s ../x86_64-linux-gnu/libimagequant.so.0 $SNAPCRAFT_PART_INSTALL/usr/lib/rayforge-libs/libimagequant.so.0
      ln -s ../x86_64-linux-gnu/libcgif.so.0 $SNAPCRAFT_PART_INSTALL/usr/lib/rayforge-libs/libcgif.so.0
      ln -s ../x86_64-linux-gnu/libexif.so.12 $SNAPCRAFT_PART_INSTALL/usr/lib/rayforge-libs/libexif.so.12
      ln -s ../x86_64-linux-gnu/libspng.so.0 $SNAPCRAFT_PART_INSTALL/usr/lib/rayforge-libs/libspng.so.0
      ln -s ../x86_64-linux-gnu/libmatio.so.11 $SNAPCRAFT_PART_INSTALL/usr/lib/rayforge-libs/libmatio.so.11
      ln -s ../x86_64-linux-gnu/libOpenEXR-3_1.so.30 $SNAPCRAFT_PART_INSTALL/usr/lib/rayforge-libs/libOpenEXR-3_1.so.30
      ln -s ../x86_64-linux-gnu/libhwy.so.1 $SNAPCRAFT_PART_INSTALL/usr/lib/rayforge-libs/libhwy.so.1
      ln -s ../x86_64-linux-gnu/libhdf5_serial.so.103 $SNAPCRAFT_PART_INSTALL/usr/lib/rayforge-libs/libhdf5_serial.so.103
      ln -s ../x86_64-linux-gnu/libImath-3_1.so.29 $SNAPCRAFT_PART_INSTALL/usr/lib/rayforge-libs/libImath-3_1.so.29
      ln -s ../x86_64-linux-gnu/libIlmThread-3_1.so.30 $SNAPCRAFT_PART_INSTALL/usr/lib/rayforge-libs/libIlmThread-3_1.so.30
      ln -s ../x86_64-linux-gnu/libIex-3_1.so.30 $SNAPCRAFT_PART_INSTALL/usr/lib/rayforge-libs/libIex-3_1.so.30
      ln -s ../x86_64-linux-gnu/libsz.so.2 $SNAPCRAFT_PART_INSTALL/usr/lib/rayforge-libs/libsz.so.2
      ln -s ../x86_64-linux-gnu/libaec.so.0 $SNAPCRAFT_PART_INSTALL/usr/lib/rayforge-libs/libaec.so.0

      snapcraftctl build
